### ISSUE TITLE
server freeze possible caused by this mod?

### ISSUE THREAD

**Issue by Fenekhu** [Alex-MacLean/TheLegendOfHerobrine#1]
I don't have much to go on because there's no information in any logs or anything but removing this mod seems to have fixed it.
I was exploring in a singleplayer world when I noticed the chunks had stopped generating. One Probe said "waiting for server" and general game logic was completely frozen. I had to force it closed with task manager and tried approaching that same location from multiple sides but each time the same thing happened. I began removing all mods that add entity spawns and world gen mods one by one and removing this one seemed to have fixed it.

Minecraft: 1.15.2
Forge: 31.1.77
this mod: 0.4.3

**Comment by Alex-MacLean** [comment]
Do you still have the latest.log file in .minecraft/logs or an archived log from when this issue appeared?
What other mods were loaded?
What version of java do you use (OpenJDK, JRE, Oracle JDK), and what update.
Can you send any screenshots or recordings of this issue occuring?
Thank you for reporting this issue. I will look into this problem as soon as possible.

**Comment by Fenekhu** [comment]
I have the logs from when it happened. I was just looking at the console window but it turns out i had it only showing INFO messages. here is the everything was printed to the console since i joined the world the last two times it happened:
https://gist.github.com/TheGoldenProof/b5fbb46d1be7f202cabf9b2d96bebd0c
I thought it was using a more recent version of java but the logs say its using `java version 1.8.0_51 by Oracle Corporation`
I don't even have that version installed so I guess minecraft must come with its own jre.
I had been exploring for a while so I don't know how i can reproduce it other than just flying around for hours.
I've got about 175 mods. I think you could probably understand that I don't want to type them all out by hand. Is there some other way to quickly generate a copy-and-pasteable list of mods installed?

**Comment by Alex-MacLean** [comment]
The log files didn't seem to contain any information about that bug. 
The mod this probably isn't needed because this mod doesn't really do much to cause compatibility problems.
If you kept removing mods has removing any other mod fixed the problem, because that would mean there is in fact a compatibility issue.
This mod was tested to work on java 1.8.0_241 and 1.8.0_251, so that may help the problem. 
Also try allocating more RAM to Minecraft if you have not already because many mods can be resource heavy.
If you have tried to get this working again has the problem persisted, or seemingly solved it's self?

**Comment by Fenekhu** [comment]
I thought I was using 1.8.0_251. I have plenty of RAM allocated, like 10GB. Its not a RAM issue. I didn't have the mod installed and it just happened again in a different place. Guess its back to removing mods again.

**Comment by Alex-MacLean** [comment]
Thank you for reporting this issue, it may not have been a problem with this mod, but I really appreciate you going out of your way to try an make this a better mod. I hope you find out what is going on with your game.
