### ISSUE TITLE
Mobs not spawning (1.15.2)

### ISSUE THREAD

**Issue by enderdragon765** [Alex-MacLean/TheLegendOfHerobrine#11]
I couldn't find any Herobrines in my world or infected mobs, I was on normal difficulty and tried spawning them in creative, didn't work, so I'm just wondering, what version of forge do you reccomend for this mod? And if it uses Fabric the mod page says otherwise.

**Comment by Alex-MacLean** [comment]
This mod does not use Fabric. Also you need to activate an Altar of Herobrine by placing it on the Netherrack of a shrine and right clicking it with a cursed diamond.
Recommended Forge is Forge 31.2.36, which is the latest as of writing this.

Shrine:
![2020-07-03_22](https://user-images.githubusercontent.com/59214922/89700506-6bca4e00-d8fc-11ea-834d-0ca8134ee3ff.png)

**Comment by enderdragon765** [comment]
That's what I have done in both worlds, I have placed the altar, activated
it, and it wont spawn the mobs naturally or let me spawn them with eggs.

**Comment by Alex-MacLean** [comment]
Try deactivating it by right clicking it with a purified diamond, then re activate it with the cursed diamond. If it works it should strike lightning and send a chat message
