### ISSUE TITLE
Mobs from the mod appear Invisible when used in Multiplayer

### ISSUE THREAD

**Issue by Wolfgalaxy63** [Alex-MacLean/TheLegendOfHerobrine#15]
I put the mod on a private server for a few friends and I, and everything seemed to work fine at first, the structures and everything appeared fine. But eventually, once the Mobs started spawning, nobody except for me could see them, including the versions of Herobrine himself. After restarting the server, then nobody could see them, not even me. This server has multiple mods on it, so it could be some kind of conflict, but at the same time, I don't think any of the mods on the server would conflict with this one, since they all do pretty isolated things.

Also, the lag was cut down majorly once I removed the mod, so it was causing some type of lag. Is this a known issue, or is it something that I'm personally doing wrong?

EDIT: I'm using 1.12.2 for all of this.
EDIT 2: We switched some mods out, and I decided to bring this one back to experiment. It didn't cause any lag, however, the mobs were still invisible to everyone but me.

**Comment by Alex-MacLean** [comment]
This is a very strange issue. The data for whether Herobrine should spawn is stored in World/data/herobrine_worldvars.dat so there should not be any conflict between client and server if the client is properly returning the information stored in that file. It seems like when someone connects to the world the client is for some reason unable to properly reference that file so it uses the default value for the "Spawn" Boolean, which is "false". The server is able to properly read that so the file does work somewhat properly. A theoretical fix would be to add an if statement to only run the code that removes Herobrine on the server side, but that may cause other issues on the client side.

**Comment by Alex-MacLean** [comment]
I've done some experimenting with !world.isRemote checks and from what testing I could do everything seems to work fine both on Singleplayer and Multiplayer. I just added !world.isRemote to the code that despawns Herobrine and removed unnecessary ones from the code that syncs the data when the world is loaded. I plan on releasing this patch in the 0.5.3 update later today, which also should fix the other issues currently on the issue tracker. If this issue still exists after the 0.5.3 update please let me know so I can look for another solution.

**Comment by Alex-MacLean** [comment]
Presumably fixed in 0.5.3. If this still persists I'll re open the issue.
