### ISSUE TITLE
question

### ISSUE THREAD

**Issue by brice0507** [Alex-MacLean/TheLegendOfHerobrine#16]
I don't understand how to spawn Herobrine

**Comment by Alex-MacLean** [comment]
You first need to build a shrine, there is a screenshot below showing what it looks like. Next you need to craft and place an Altar of Herobrine on the center of the shrine, directly on the netherrack. Finally you need to craft a Cursed Diamond and right click the Altar of Herobrine with the Cursed Diamond, if it was done correctly lightning should strike the Altar and a chat message should display.

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/59214922/96802878-cbeb6f00-13d8-11eb-98b0-22c56beface8.png)

If you have any future questions I would see it faster if you commented on the mods Curseforge page or sent me a message on Curseforge
