### ISSUE TITLE
Some suggestions to make this mod a bit more spooky and nostalgic

### ISSUE THREAD

**Issue by Scapulaunit12** [Alex-MacLean/TheLegendOfHerobrine#20]
Hello, I love this mod and I think its great but there are some areas that I think should improve.

One way we can make this mod a whole lot scarier is if the herobrine stalker instead of running away disapears after a little bit with smoke particles if you look at him. It could also play some spooky cave ambience when it does so. The herobrine stalker should also spawn more frequently than the other herobrines. 

Spooky ambience can also play when a herobrine builder constructs something. He should also disappear when complete.

Another feature this mod can have is in the config to make it so that you spawn herobrine in the old mod. This could either be with the column with the herobrine netherrack in the middle or the classic 3x3 altar.

**Comment by Alex-MacLean** [comment]
Those are really good suggestions. I plan on overhauling the AI for Herobrine soon so I will make a lot of changes to the Herobrine Spy.

**Comment by mykytache** [comment]
> Those are really good suggestions. I plan on overhauling the AI for Herobrine soon so I will make a lot of changes to the Herobrine Spy.

Wow, sounds like a great plan. 
Looking forward.
Thanks for contributing.
