### ISSUE TITLE
Singleplayer stuck on 'saving world' screen upon leaving game

### ISSUE THREAD

**Issue by f0rtyone** [Alex-MacLean/TheLegendOfHerobrine#23]
**Describe the bug**
If you leave a singleplayer world, you'll be stuck on 'saving game' screen as you click 'save and quit to title'. The only way to fix it is to end task in task manager. You can't quit minecraft in any other way 

**To Reproduce**
Steps to reproduce this bug.

**Expected behavior**

**Screenshots**

**Environment**
 - OS: [e.g. Windows 10 64 bit]
 - Java Version: [e.g. JRE 1.8.0_51 64 bit]
 - Minecraft Version: [e.g. 1.16.5]
 - Forge Version: [e.g. 36.0.0] (If you're using an MDK environment please state that you are)
 - Mod Version: [e.g. 1.0]
 
**Additional context**

**Comment by Alex-MacLean** [comment]
Do you have any other mods installed and what version of Minecraft and Forge are you using?
