### ISSUE TITLE
Survivor Houses should generate in more reasonable ways

### ISSUE THREAD

**Issue by ehx-v1** [Alex-MacLean/TheLegendOfHerobrine#24]
Currently, the Survivor Houses have no dedicated air around their outer fences, which often leads to them being embedded into hills and having the wall become effortlessly bypassable by all creatures in existence. Given that Survivors are designed after pro players, this seems unrealistic - surely a player who's experienced enough to construct a spiderproof wall, would think of excavating a wide enough trench in the hillside?

Another problem are the overhangs that occur when the Survivor House spawns in an area with higher hills, and lead to similar inconsistencies. However, I don't think much can be done about that, except maybe prohibit it from spawning in overly hilly biomes.

And a third worldgen inconsistency: When the Survivor House spawns slightly submerged into water, for the most part the water is removed inside, but the lamppost fences and similar blocks end up being waterlogged, creating a flood both around the garden and in the house itself. I doubt any player would shrug that away as a minor inconvenience, except maybe if they have Depth Strider boots.

Either way, these are some worldgen problems that clearly aren't bugs, but seem like design oversights to me. I'd appreciate if you considered improving upon this. (Sorry if this has already been addressed, I couldn't find anything in the open or closed issues.)

**Comment by Alex-MacLean** [comment]
I have been wanting to fix many issues with the structures of this mod, especially the larger ones. I've noticed that many times they hang over hills and look a bit weird. I'll likely look into how village houses generate ground or around them when necessary so the survivor bases and trapped houses look more natural.

**Comment by Alex-MacLean** [comment]
Fixed in 0.6.5 for Fabric 1.20+
