### ISSUE TITLE
Crash Infected Horse

### ISSUE THREAD

**Issue by Deisaku** [Alex-MacLean/TheLegendOfHerobrine#25]
**Describe the bug**
My games crash when i cross an infect horse.
**To Reproduce**
I reconnect my every time i crash

[crash-2021-03-22_11.47.16-client.txt](https://github.com/Alex-MacLean/TheLegendOfHerobrine/files/6181631/crash-2021-03-22_11.47.16-client.txt)

Deisaku.

**Comment by Alex-MacLean** [comment]
1.15.2 is no longer a supported Minecraft version for this mod. I apologize for any inconvenience or issues.
