### ISSUE TITLE
Altar not working

### ISSUE THREAD

**Issue by MrRWord** [Alex-MacLean/TheLegendOfHerobrine#26]
I downloaded this mod on forge and I made the shrine properly then placed the altar above it and right clicked with the cursed diamond but NOTHING happened.I tried it on a new world too but still nothing.

**Environment**
 - Windows 10 64 bit
 - Minecraft Version: 1.16.5

**Comment by Alex-MacLean** [comment]
I have made a video showing the process. If you follow it and are still getting this issue let me know.

https://www.youtube.com/watch?v=l7tN4abAQMs
