### ISSUE TITLE
Herobrine Mobs Tracking Player

### ISSUE THREAD

**Issue by 4byterob** [Alex-MacLean/TheLegendOfHerobrine#28]
**Describe the bug**
When you get targeted by a mage Herobrine, you occasionally get "launched up" and teleport close to his position (or at least it appears that way). If you're on something like a horse and you get "lauched up," you automatically get dismounted off the horse but you leave a sort of ghost behind. Any mob that was targeting you will instead go up to the horse and tilt their heads up, as if targeting you if you were still on the horse. Weirdly enough, they can sometimes hit the 'ghost' that stays above the horse, which will actually damage the real you.

**To Reproduce**
 - Tame and get on a horse (didn't test for things like minecarts or boats yet)
 - Find and get close to a Mage Herobrine
 - Make him use his "teleport" ability
 - Results

**Expected behavior**
When you get teleported, you should expect any hostile mobs that targeted you (even vanilla ones) to target a "ghost" you on top of the horse.

**Screenshots**
![image](https://user-images.githubusercontent.com/53685232/115121599-d1cda180-9f70-11eb-9abe-c815987cfc9c.png)

**Environment**
 - OS: Windows 10 64 bit
 - Java Version: [e.g. JRE 1.8.0_51 64 bit]
 - Minecraft Version: 1.16.4
 - Forge Version: 35.1.4
 - Mod Version: 0.5.4
 
**Additional context**
I'm not sure if it was fixed in 0.6.0, I don't have the time now to check.

**Comment by Alex-MacLean** [comment]
That is a very weird glitch. I never thought of testing anything like that. That's the reason this mod is still marked as beta lol. I'll try to make it teleport the entity that is being ridden if the target is riding something but if I can't do that I'll just make it not teleport targets that are riding an entity. I have not done anything that should fix this bug in 0.6.0 so it probably still exists in 0.6.0.

**Comment by Alex-MacLean** [comment]
Update: I fixed this issue by forcing the target to dismount when being teleported. I will include this patch in the 0.6.1 update

**Comment by Alex-MacLean** [comment]
Reopened because this issue is present in the latest public release

**Comment by Alex-MacLean** [comment]
Fixed in 0.6.1
