### ISSUE TITLE
The Cursed Forest always spawns even after deactivating it.

### ISSUE THREAD

**Issue by Samlegamer** [Alex-MacLean/TheLegendOfHerobrine#30]
Hello I downloaded this mod recently and I noticed that they had a biome the Cursed Forest, I deactivated the biome with a 0 like what is marked in the config, except that in game the biome always spawn.

mod version :
1.12.2-0.5.4
![2021-07-19_23 13 09](https://user-images.githubusercontent.com/83614614/126234936-eb2f4d43-bfa9-4365-ac84-e9907ebd679c.png)
![2021-07-19_23 13 58](https://user-images.githubusercontent.com/83614614/126234939-cec33a09-d836-446f-894f-4778be7124cc.png)

**Comment by Alex-MacLean** [comment]
This is an issue with the GUI config with the 1.12.2 version of this mod which as of right now is currently not receiving updates. A workaround is to edit the config file manually in .minecraft/config/herobrine-common.cfg
