### ISSUE TITLE
Cursed forest biome can't be turned off 1.16

### ISSUE THREAD

**Issue by SheReyy** [Alex-MacLean/TheLegendOfHerobrine#33]
**Describe the bug**
After changing the spawn weight of the cursed forest in the herobrine-common.toml file, I still managed to find it. 

**Expected behavior**
The biome shouldn't spawn if its weight is set to 0.

**Environment**
 - OS: Windows 10 64 bit
 - Java Version: JRE 1.8.0_301 64 bit
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.4.0
 - Mod Version: TheLegendOfHerobrine-1.16.5-0.6.3.jar
 
**Additional context**
I managed to encounter this bug on a modpack with 226 mods.

**Comment by Alex-MacLean** [comment]
Can you say what modpack you are using or the mod list? There might be a compatibility issue with a world generation mod if there are any installed. I'll be trying to recreate this issue in a mostly vanilla environment.

**Comment by SheReyy** [comment]
[This](https://www.curseforge.com/minecraft/modpacks/decursio-project/files) is my pack where I encountered the issue. I haven't tested it, but maybe you could use a Nature's Compass to find the biome if it still spawns (I say this because I changed some things in the pack, maybe the issue is gone).

**Comment by Alex-MacLean** [comment]
I have confirmed this bug exists when I'm using this mod alone so it is not a compatibility issue with another mod. I just created a world and used the /locate command after changing the config.

**Comment by Alex-MacLean** [comment]
No longer working on the Forge 1.16.5 version. This bug was fixed in the Fabric 1.20 version and Cursed Forest can be disabled by setting the min and max weirdness value above 1.0 in the config
