### ISSUE TITLE
Broken Survivors Bases

### ISSUE THREAD

**Issue by ChrisLTheNerd** [Alex-MacLean/TheLegendOfHerobrine#34]
**Describe the bug**
Sometimes survivors bases will spawn with parts of the outer wall missing

**Screenshots**

![2021-10-15_20 43 21](https://user-images.githubusercontent.com/50182206/137567110-c853df21-a2a9-4faa-8bbd-ff76dd786810.png)

**Environment**
 - OS: Windows 10 64 bit
 - Java Version: JRE 8.0.3010.9 64 bit
 - Minecraft Version: 1.16.5]
 - Forge Version: 36.2.4
 - Mod Version: 1.16.5-0.6.3

**Comment by Alex-MacLean** [comment]
This is a bug with Vanilla Minecraft and larger structures sometimes getting cut off by chunk borders therefore I am unable to fix this issue
