### ISSUE TITLE
(1.12.2) conflict with champions mod

### ISSUE THREAD

**Issue by rebarakuk** [Alex-MacLean/TheLegendOfHerobrine#35]
**Describe the bug**
When monsters were fighting each other at night, this crash suddenly happened

**To Reproduce**
Steps to reproduce this bug.
1. time set to night
2. monsters fighting each other

**Expected behavior**
they fight each other

**Screenshots**

**Environment**
 - OS: Windows 10 64 bit
 - Java Version: 1.8.0_321 b07 64bit
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2860
 - the legend of herobrine Mod Version: 0.5.4
 - champions mod version: 1.0.11.10
 
**Additional context**

here is the crash log:
https://gist.github.com/rebarakuk/ff3f6cfc7fd3f84ef88a9613d21003c1

**Comment by Alex-MacLean** [comment]
Legacy 1.12.2 is no longer being worked on since I don't have the time to keep multiple branches open by myself
