### ISSUE TITLE
1.16.5 game crashes with new world

### ISSUE THREAD

**Issue by papertek** [Alex-MacLean/TheLegendOfHerobrine#36]
**Expected behavior**
no crashing

**Environment**
 - OS: [Windows 10 64 bit]
 - Minecraft Version: [1.16.5]
 - Forge Version: [36.2.34]
 - Mod Version: [0.6.3]
 
**Additional context**
so while playing i loaded chunks unexpectedly while it was a new world, herobrine is spawned in by default and my configs make him see the player from 40 or more blocks away

logs
[crash-2022-05-05_23.08.00-server.txt](https://github.com/Alex-MacLean/TheLegendOfHerobrine/files/8637482/crash-2022-05-05_23.08.00-server.txt)

**Comment by papertek** [comment]
actually this might be a structure issue :/

**Comment by Alex-MacLean** [comment]
This looks like an issue with one of the structure mods, likely repurposed structures, or better mineshafts, or better strongholds
