### ISSUE TITLE
1.16.5 crash with corpse

### ISSUE THREAD

**Issue by papertek** [Alex-MacLean/TheLegendOfHerobrine#37]
**Describe the bug**
when my friend opened a corpse their game crashed with ticking entity, im not sure if this mod is the problem

**To Reproduce**
Open a corpse when you die and have herobrine stalker in

**Screenshots**
no screenshots but heres a crash link instead
https://bytebin.lucko.me/kpFCDk40EO

**Environment**
this was on a friends pc so i dont have much info
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.34 
 - Mod Version: 0.6.3

**Comment by Alex-MacLean** [comment]
This likely isn't a bug with The Legend of Herobrine
