### ISSUE TITLE
Spawning

### ISSUE THREAD

**Issue by DaddyGhast** [Alex-MacLean/TheLegendOfHerobrine#38]
**Describe the bug**
When I am spawning herobrine mobs they vanish instantly 

**To Reproduce**
Steps to reproduce this bug.

**Expected behavior**
There supposed to spawn.

**Screenshots**

**Environment**
 - OS: [e.g. Windows 10 64 bit]
 - Java Version: [e.g. JRE 1.8.0_51 64 bit]
 - Minecraft Version: [e.g. 1.16.5]
 - Forge Version: [e.g. 36.0.0] (If you're using an MDK environment please state that you are)
 - Mod Version: [e.g. 1.0]
 
**Additional context**
I dont have any videos or pictures

**Comment by Alex-MacLean** [comment]
You need to activate an Altar of Herobrine or enable HerobrineAlwaysSpawns in the config first
