### ISSUE TITLE
1.19.2 support?

### ISSUE THREAD

**Issue by kristibektashi** [Alex-MacLean/TheLegendOfHerobrine#39]
**Description**
I would like to use this mod on Minecraft 1.19.2

**Comment by Wubzzz1337** [comment]
https://github.com/Alex-MacLean/TheLegendOfHerobrine-Preview/issues/1
He has a 1.19.3 version :/

**Comment by Alex-MacLean** [comment]
0.6.5 for Fabric 1.20+ released
