### ISSUE TITLE
Stop spawning so many herobrines at once

### ISSUE THREAD

**Issue by official-brucewayne** [Alex-MacLean/TheLegendOfHerobrine#40]
So I had the thought that in herobrine lore, you don't come across like 4 herobrines at once so maybe consider removing the mage clone feature and stop them from spawning so close to each other. Also this is not a complaint just a simple suggestion so don't take it the wrong way, thanks :D

**Comment by Alex-MacLean** [comment]
Due to How mob spawning works in Minecraft I can't control how many spawn at once, only change how frequently Herobrine spawns. The new version for Fabric 1.20.1 has lower spawn rates by default and they can be changed in the config
