### ISSUE TITLE
immortal baby hust

### ISSUE THREAD

**Issue by kodamant** [Alex-MacLean/TheLegendOfHerobrine#42]
baby husks, only when spawning naturally, are immune to all forms of attack

**To Reproduce**
step one: have fun in minecraft
step two: find possesed baby husk
step three: contain the anomaly

**Expected behavior**
well i expected to be able to kill it

**Environment**
 - Minecraft Version:1.20.1
 - Mod Version:1.0.7.2

**Comment by kodamant** [comment]
https://imgur.com/a/gsL9PqW

**Comment by kodamant** [comment]
ok so new info, if i switch into creative to hit said baby husk it is suddenly mortal

**Comment by Alex-MacLean** [comment]
This mod does not add possessed versions of already hostile mobs. I did a bit of research and it looks like an issue with the Forge mod "The End of Herobrine" I'd recommend going on their GitHub and opening an issue there. I'll take a look at the source code myself to see if I can find a solution to the issue. It looks like the creator made an attempt to fix it, but it looks like it still exists

**Comment by kodamant** [comment]
oh, this is the wrong herobrine mod, sorry, its late, thanks though

**Comment by Alex-MacLean** [comment]
Thank you for spending the time to make an issue report. It can get a bit confusing with 3 herobrine mods existing in modern versions of Minecraft so I get it
