### ISSUE TITLE
Biome blacklist

### ISSUE THREAD

**Issue by mpustovoi** [Alex-MacLean/TheLegendOfHerobrine#43]
**Description**
Blacklist for biomes/dimensions in which any Herobrine won't spawn at all

**Concept Art**
When installing datapack like "The Bracken Pack", which adds a dimension where there shouldn't be any mobs at all (the Void), an extremely large number of Herobrines appear there. I know that it's impossible to reduce their number, so it would be useful to be able to completely disable spawning of Herobrine in specific biomes/dimensions.

**Comment by mpustovoi** [comment]
I guess there may be a way to edit this in your datapack files. However, I don't know where it could possibly be. Will be glad if you tell me.

**Comment by Alex-MacLean** [comment]
My mod adds Herobrine to every biome to try and be compatible with modded biomes and out of bounds biomes like "The Void" typically aren't in an area where any mobs can spawn. The spawns are added through code with my mod, but it may be possible to create a datapack overriding this behavior. A compatibility patch shouldn't be too hard, just change "BiomeSelectors.all" which selects every biome to "BiomeSelectors.excludeByKey()" where I can exclude certain biomes like "The Void".

I'll get to work on a fix soon after I wake up a bit more

**Comment by Alex-MacLean** [comment]
I just released a fix for this issue in version 0.7.2
