### ISSUE TITLE
nessun segno di herobrine

### ISSUE THREAD

**Issue by qwerty08wewg** [Alex-MacLean/TheLegendOfHerobrine#45]
**Describe the bug**
quando metto la mod ce tutto l'altare il diamante corrotto ecc..  per quando evoco herobrine non seccede niente nessun mostro maledetto e nessuna varuante di herobrine versione 1.20.1 fabric ultima release

**To Reproduce**
Steps to reproduce this bug.

**Expected behavior**

**Screenshots**

**Environment**
 - OS: [e.g. Windows 11 64 bit] (If you are using GNU/Linux state the distro and kernel branch and version e.g. Arch Linux - 6.4.2-zen1-1-zen. Can easily be found in neofetch)
 - Java Version: [e.g. JRE 17.0.1 64 bit]
 - Minecraft Version: [e.g. 1.20.1]
 - Fabric/Quilt Version: [e.g. 0.14.21] (If you're using a development environment please state that you are)
 - Fabric API/QFAPI+QSL Version: [e.g. 0.83.0]
 - Mod Version: [e.g. 1.0]

**Additional context**

**Comment by Alex-MacLean** [comment]
Ti invitiamo a seguire questa guida se non l'hai già fatto. I blocchi d'oro nella ricetta di creazione dell'Altare ora sono lingotti d'oro, ma per il resto i passaggi sono identici alla guida: 

[https://www.youtube.com/watch?v=l7tN4abAQMs](url)

Con l'ultimo aggiornamento Herobrine ora avanza in fasi con 4 fasi in totale. All'inizio non succederà molto, ma dopo circa 3 giorni di gioco ogni variante verrà generata in modo naturale. Per favore riapri questo problema se ho capito male o c'è un problema con il mod. Funziona sul mio computer, ma ogni configurazione è diversa e ciò che potrebbe funzionare per me potrebbe non funzionare per tutti
(Ci scusiamo per eventuali problemi grammaticali. Sto utilizzando Google Translate poiché l'italiano non è la mia lingua madre ed è la lingua rilevata da Google Translate)
