### ISSUE TITLE
Curing infected mobs

### ISSUE THREAD

**Issue by PercyJames** [Alex-MacLean/TheLegendOfHerobrine#5]
**Is your feature request related to a problem? Please describe.**
there isn't any way to cure infected mobs.

**Describe the solution you'd like**
maybe curing infected mobs could work like curing a zombie villager but with holy water and an enchanted golden apple.

 1: you splash the holy water on the mob

 2: feed enchanted golden apple

 3: wait 2-5 minutes

 4: profit

**Describe alternatives you've considered**
craft 8 holy waters and an enchanted golden apple to get a "Healing Thing" basically a cross. but it's the mojang logo
![cured](https://user-images.githubusercontent.com/65469481/84330846-18cb5900-ab4e-11ea-8909-bcccd7770b35.png)

**Additional context**

**Comment by Alex-MacLean** [comment]
I just implemented a way to cure infected mobs by throwing holy water on them. This or the crafting recipe for Holy water may change to ingots or even blocks because this could be unbalanced. I am still open to new ideas around this feature though.

**Comment by PercyJames** [comment]
ok! i hope i helped in some way!
