### ISSUE TITLE
Game Crash when both the Mimic from the Artifacts Mod and the Survivor are loaded at a certain distance

### ISSUE THREAD

**Issue by HueyCan** [Alex-MacLean/TheLegendOfHerobrine#52]
**Describe the bug**
When the Mimic from the [Artifacts](https://modrinth.com/mod/artifacts) Mod is loaded close enough to a Survivor, the game will crash

**To Reproduce**
Simply spawn the Mimic and the Survivor anywhere near each other

**Expected behavior**
No crash, with either having both mobs interact or no interaction

**Environment**
 - OS: Windows 11 Home 64 bit
 - Java Version: 21.0.1
 - Minecraft Version: 1.20.1
 - Fabric Version: 0.15.7
 - Fabric API Version: 0.92.0
 - Mod Version: 0.7.2

**Additional context**
[Video](https://github.com/Alex-MacLean/TheLegendOfHerobrine/assets/31521545/26594f47-06e0-4e43-b82e-f81af56df26c)

**Comment by Alex-MacLean** [comment]
This appears to be the same issue as #47. Closing since it appears to be a duplicate
