### ISSUE TITLE
Survivor Crash?

### ISSUE THREAD

**Issue by BrandonPotter0** [Alex-MacLean/TheLegendOfHerobrine#54]
**Describe the bug**
Might be an incompatibility with The Man from the Fog Reimagined, Im not entirely sure. I was just standing in the base, trying to expand the survivors house, and I was looking at the Survivor, and BAM. Crash.

**To Reproduce**
Just wait around in a survivor base?

**Expected behavior**
Uh, Not Crash Randomly? 

**Screenshots**
[crash-2024-09-20_08.16.24-server.txt](https://github.com/user-attachments/files/17077240/crash-2024-09-20_08.16.24-server.txt)

**Environment**
 - OS: Windows 11, 64 Bit
 - Java Version: 21.0.1, Eclipse Adoptium
 - Minecraft Version:  1.20.1
 - Fabric/Quilt Version: 0.16.5
 - Fabric API/QFAPI+QSL Version: 0.92.2
 - Mod Version: 0.7.2

**Additional context**
`---- Minecraft Crash Report ----
// My bad.

Time: 2024-09-20 08:16:24
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1621 cannot be cast to class net.minecraft.class_1588 (net.minecraft.class_1621 and net.minecraft.class_1588 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66a3ffec)
	at com.herobrinemod.herobrine.entities.SurvivorEntity.method_5958(SurvivorEntity.java:154)
	at net.minecraft.class_1308.method_6023(class_1308.java:788)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.herobrinemod.herobrine.entities.SurvivorEntity.method_5958(SurvivorEntity.java:154)
	at net.minecraft.class_1308.method_6023(class_1308.java:788)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: herobrine:survivor (com.herobrinemod.herobrine.entities.SurvivorEntity)
	Entity ID: 778
	Entity Name: Survivor
	Entity's Exact location: 170.76, 63.00, 337.77
	Entity's Block location: World: (170,63,337), Section: (at 10,15,1 in 10,3,21; chunk contains blocks 160,-64,336 to 175,319,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['BrandonPotter0'/222, l='ServerLevel[New World]', x=168.35, y=63.00, z=330.62]]
	Chunk stats: 2694
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,75,144), Section: (at 0,11,0 in 8,4,9; chunk contains blocks 128,-64,144 to 143,319,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 13289 game time, 13289 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 156007 (now: false), thunder time: 118281 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1403817248 bytes (1338 MiB) / 3045064704 bytes (2904 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7700 8-Core Processor              
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2786
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6094
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x164e
	Graphics card #1 versionInfo: DriverVersion=31.0.24002.92
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 36575.54
	Virtual memory used (MB): 16839.96
	Swap memory total (MB): 4608.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		accessories: Accessories 1.0.0-beta.35+1.20.1
			io_wispforest_endec: endec 0.1.8
			io_wispforest_endec_gson: gson 0.1.5
			io_wispforest_endec_netty: netty 0.1.4
		amendments: Amendments 1.20-1.2.11
		ancientreforging: Ancient Reforging 1.2.2-fabric
		animation_overhaul: Animation Overhaul 1.3.1
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		artifacts: Artifacts 9.5.13
			expandability: ExpandAbility 9.0.4
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		attributefix: AttributeFix 21.0.4
		balm-fabric: Balm 7.3.9
			kuma_api: KumaAPI 20.1.8
		betteranimationscollection: Better Animations Collection 8.0.0
		bookshelf: Bookshelf 20.2.13
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		charmofundying: Charm of Undying 6.5.0+1.20.1
			spectrelib: SpectreLib 0.13.15+1.20.1
		cloth-config: Cloth Config v11 11.1.136
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.84
		connectedglass: Connected Glass 1.1.12
		coroutil: CoroUtil 1.20.1-1.3.7
		cosmetic-armor: Cosmetic Armor 1.6.0
		creeperoverhaul: Creeper Overhaul 3.0.2
		croptopia: Croptopia 3.0.3
		crowdcontrol: Crowd Control 3.3.5+fabric-1.20.1
			adventure-platform-fabric: adventure-platform-fabric 5.9.0
				net_kyori_adventure-api: adventure-api 4.14.0
				net_kyori_adventure-key: adventure-key 4.14.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.14.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.14.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.14.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.14.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.14.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.14.0
				net_kyori_ansi: ansi 1.0.2
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			cloud: Cloud 1.8.4
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.8.4
				cloud_commandframework_cloud-core_: cloud-core 1.8.4
				cloud_commandframework_cloud-services_: cloud-services 1.8.4
				fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
				io_leangen_geantyref_geantyref: geantyref 1.3.13
		dsurround: Dynamic Surroundings 0.3.3
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.4
		dynamiclights: Dynamic Lights 1.8.3+mod
		easyanvils: Easy Anvils 8.0.2
		elytraslot: Elytra Slot 6.4.2+1.20.1
			mixinsquared: MixinSquared 0.1.2-beta.6
		enchdesc: EnchantmentDescriptions 17.1.18
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		epherolib: EpheroLib 1.2.0
		everycomp: Every Compat 1.20-2.6.76
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				com_electronwill_night-config_core: core 3.6.6
				com_electronwill_night-config_toml: toml 3.6.6
				porting_lib_config: Porting Lib Config 2.3.4+1.20.1
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
			porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_model_generators: Porting Lib Model Generators 2.3.4+1.20.1
				porting_lib_data: Porting Lib Data 2.3.4+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			porting_lib_models: Porting Lib Models 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.6
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.7
		expanded_bow_enchanting: Expanded Bow Enchanting 1.0.0
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.6
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.2+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.2
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		fakerlib: fakerlib 0.1.4
		forgeconfigapiport: Forge Config API Port 8.0.0
		forgivingvoid: Forgiving Void 10.0.1
		fusion: Fusion 1.1.1
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		herobrine: The Legend of Herobrine 0.7.2
		indium: Indium 1.0.34+mc1.20.1
		iris: Iris 1.7.2+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 11.11.0+fabric
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 15.19.5.99
		languagereload: Language Reload 1.6.1+1.20.1
		majruszlibrary: Majrusz Library 7.0.8
		majruszsaccessories: Majrusz's Accessories 1.5.3
		mcwdoors: Macaw's Doors 1.1.1
		mcwfences: Macaw's Fences and Walls 1.1.2
		mcwfurnitures: Macaw's Furniture 3.3.0
		mcwholidays: Macaw's Holidays 1.1.0
		mcwlights: Macaw's Lights and Lamps 1.1.1
		mcwpaintings: Macaw's Paintings 1.0.5
		mcwtrpdoors: Macaw's Trapdoors 1.1.3
		mcwwindows: Macaw's Windows 2.3.0
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.19.4+mc1.20.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.13.0
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3.f
		necronomicon: Necronomicon 1.4.2
		player-animator: Player Animator 1.0.2-rc1+1.20
		puzzleslib: Puzzles Lib 8.1.23
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		radiantgear: Radiant Gear 2.1.6+1.20.1
		repurposed_structures: Repurposed Structures 7.1.15+1.20.1-fabric
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.29
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sophisticatedbackpacks: Sophisticated Backpacks 3.19.5+mc1.20.1-SNAPSHOT-build.104
			team_reborn_energy: Energy 3.0.0
		sophisticatedcore: Sophisticated Core 0.5.109+mc1.20.1-SNAPSHOT-build.104
		sophisticatedstorage: Sophisticated Storage 0.8.60+mc1.20.1-SNAPSHOT-build.104
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.4.5
		spell_engine: Spell Engine 0.15.11+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		spell_power: Spell Power Attribute 0.12.0+1.20.1
		stackrefill: Stack Refill 4.5
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+a
		supplementaries: Supplementaries 1.20-2.8.17
		tclayer: Accessories Trinkets Compat Layer 3.8.1+beta.11
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
		the_fog_is_coming: Man From The Fog 0.5.19
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		trashcans: Trash Cans 1.0.18
		watching: From The Fog 1.9.2
		xaerominimap: Xaero's Minimap 24.4.0
		xaeroworldmap: Xaero's World Map 1.39.0
		youritemsaresafe: Your Items Are Safe 4.5
		zenith: Zenith 1.2.3-1.20.1
			mm: Manningham Mills 2.3
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_model_materials: Porting Lib Model Materials 2.3.4+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
			porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
		zenith_attributes: Zenith Attributes 0.2.7
			additionalentityattributes: Additional Entity Attributes 1.7.3+1.20.0
			playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		zephyr: Zephyr 0.5.0+1.20.1
	Loaded Shaderpack: ComplementaryUnbound_r5.2.2.zip
		Profile: HIGH (+1 option changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['BrandonPotter0'/222, l='ServerLevel[New World]', x=168.35, y=63.00, z=330.62]]
	Data Packs: vanilla, fabric, zenith:structures, zephyr:zephyr_zenith, Everycomp Generated Pack, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1`

**Comment by Alex-MacLean** [comment]
Looks like the same issue as #47, I already fixed it in my development versions which I am testing before I release the 0.8 update
